### ISSUE TITLE
参考リンク等  Q00-Q09

### ISSUE THREAD

**Issue by cipron81** [training-nlp-noob/knock100#2]
参考リンクとかをコメントしていくissue

**Comment by cipron81** [comment]
Q5
http://qiita.com/da1/items/771f035096e5886b6051

**Comment by kunisawa-fc** [comment]
Q5
http://en.wikipedia.org/wiki/N-gram
CharacterとWordのほかに、まあ想像通りだけどDNAとかが主な使い道かな。

**Comment by kunisawa-fc** [comment]
Q8　とりあえず自分用
http://ameblo.jp/orangeapple1/entry-10816691928.html
http://docs.python.jp/2.6/library/functions.html
http://docs.python.jp/2/library/curses.ascii.html
条件分岐
http://www.pythonweb.jp/tutorial/if/index8.html

**Comment by kunisawa-fc** [comment]
Q8　大文字小文字判別、ただし今後、複数文字列を判別の時は注意が必要
http://d.hatena.ne.jp/nakamura001/20080621/1214032669
